---
title: "python notes"
author: "JM_Wiggins"
date: '2022-06-03'
output: html_document
---

iPython: interactive python, part of the Jupiter ecosystem  

## Python command line
to enter: $python3
to exit: exit()
to exit

to create a python file/script use extension `.py`
to execute:

while in python command line (have done the steps above)
```{python eval=FALSE}
myfile.py
```


while outside of the python command line (have not done the steps above)
```{python eval=FALSE}
python3 myfile.py
```


## Indentation
indicates a code block
`print()` must be indented to be recognized as part of the `if` statement
number of spaces in the indentation must be >1 and must be consistent for the whole code block
```{python eval=FALSE}
#correct
if 5 > 2:
  print("Five is greater than two")
  
#incorrect
if 5 > 2:
print("Five is greater than two")

#correct
if 0 < 3:
  print("duh")
  print("of course zero is less than 3")

#incorrect
if 0 > 3:
  print("nope")
    print("this indentation is inconsistent")
```


## Variables
assign with `=`
```{python}
x = 22
#python is case sensative, using a capitol X will create a different variable
X = "Capitol X"
#X will not overwrite x

cow = "Holy Cow!"
#note single or double quates can be used the above is equivalent to 
#cow = 'Holy Cow!'

print(x)
print(X)
print(cow)

```

### Variable [types (classes)](https://www.w3schools.com/python/python_datatypes.asp)
to get a variable type (class):
```{python}
type(x) #print is not required
type(cow)
```

## Different data types produce different behavior
```{python}
2 + 3

'ab' + 'cd'
```
a `float` (floating point) us a number that has both an integer and a fractional part: e.g. `1.1`  
  
### Variable names
must start with a letter (e.g. `a`) or an underscore `_`
```{python}
#a few examples of strings
myvar = "works"
_myvar = "also works"
myvar2 = "works 2"

#booleans
dog = False
cat = True
```

## Convert variables:
```{python}
integer_variable = 34
#convert to string
str(integer_variable)
```

## Integers can be multiplied but not added to a number
```{python}
#works
"I said " + ("Hey " * 2) + "Hey!"
#throws an error
"The correct answer to this multiple choice exercise is answer number " + 2
```

####Camel Case
```{python}
#lowerUpperUpperUpper etc
myVariableName = "Camel"
```

####Snake Case
```{python}
#word_underscore_word_underscore
my_variable_name = "Snake"
```

Above `x` is an integer and `y` is a string automatically.
To specify the data type use casting

#### Casting
```{python}
x = str(3)    # x will be the string '3'
y = int(3)    # y will be the integer 3
z = float(3)  # z will be 3.0 (contains a decimal)
```

### Multiple Variables
```{python}
a, b, c = "Alligator", "Baboon", "Crocadile" 
print(a)
print(b)
print(c)
```

### Unpack lists or tuples
```{python}
yum = ["mango", "strawberries", "pineapple"]
m, s, p = yum
print(m)
print(s)
print(p)
```

Can also `print` the whole list
```{python}
print(m, s, p)
```

To keep the words from runnign together add spaces to the original assignments
```{python}
yum = ["mango ", "strawberries ", "pineapple "]
m, s, p = yum
print(m, s, p)
```

## Comments
```{python}
#will not be executed

"""
create a string literal for 
easy multiline comments
python will ignore this
because it wasn't assigned to a variable
"""
```

## [Operators](https://www.w3schools.com/python/python_operators.asp)
Exponentiation: ** raises the number on its left to the number on its right  
```{python}
4**2
```
Modulo: % returns the remainder of the division of the number on its left by the number on its right
```{python}
18 % 7
```


